'use client';
import { ChangeEvent, DragEvent, useEffect, useMemo, useState } from 'react';
import Papa from 'papaparse';

type Row = Record<string, string>;
type Lead = { id: number; name: string; email: string; phone: string; company: string; status: string };
type Result = { records: Row[]; totalImported: number; totalSkipped: number };
type Section = 'Dashboard' | 'Generate Leads' | 'Manage Leads' | 'Engage Leads' | 'Team Members' | 'Lead Sources' | 'Ad Accounts' | 'WhatsApp Account' | 'Tele Calling' | 'CRM Fields' | 'API Center' | 'Business Center' | 'Account Settings';
const sections: { group: string; label: Section; icon: string }[] = [
  { group: 'MAIN', label: 'Dashboard', icon: '⌂' }, { group: 'MAIN', label: 'Generate Leads', icon: '⚡' }, { group: 'MAIN', label: 'Manage Leads', icon: '▣' }, { group: 'MAIN', label: 'Engage Leads', icon: '□' },
  { group: 'CONTROL CENTER', label: 'Team Members', icon: '♧' }, { group: 'CONTROL CENTER', label: 'Lead Sources', icon: '↗' }, { group: 'CONTROL CENTER', label: 'Ad Accounts', icon: '⌘' }, { group: 'CONTROL CENTER', label: 'WhatsApp Account', icon: '▱' }, { group: 'CONTROL CENTER', label: 'Tele Calling', icon: '◉' }, { group: 'CONTROL CENTER', label: 'CRM Fields', icon: '▤' }, { group: 'CONTROL CENTER', label: 'API Center', icon: '⌁' }
];
const initialLeads: Lead[] = [
  { id: 1, name: 'Abhraneel Dhar', email: 'abhraneeldhar7@groweasy.io', phone: '+91 9051589728', company: 'GrowEasy', status: 'Good Lead' },
  { id: 2, name: 'Sarah Johnson', email: 'sarah@techsolutions.com', phone: '+91 9876543211', company: 'Tech Solutions', status: 'Not Dialed' },
  { id: 3, name: 'Rajesh Patel', email: 'rajesh@startup.inc', phone: '+91 9876543212', company: 'Startup Inc', status: 'Follow up' }
];

export default function Home() {
  const [active, setActive] = useState<Section>('Manage Leads'); const [leads, setLeads] = useState<Lead[]>(initialLeads); const [notice, setNotice] = useState(''); const [accountOpen, setAccountOpen] = useState(false); const [importOpen, setImportOpen] = useState(false);
  useEffect(() => { fetch('http://localhost:4000/api/state').then(r => r.ok ? r.json() : null).then(store => { if (store?.leads?.length) setLeads(store.leads.map((lead: Row & { id?: string; status?: string }) => ({ id: Number(lead.id?.replace?.(/\D/g, '').slice(-8)) || Date.now() + Math.random(), name: lead.name || 'Unnamed lead', email: lead.email || '', phone: lead.phone || [lead.country_code, lead.mobile_without_country_code].filter(Boolean).join(' '), company: lead.company || '—', status: lead.status || lead.crm_status || 'Not Dialed' }))); }).catch(() => undefined); }, []);
  const act = (message: string, type = 'action', details: Record<string, unknown> = {}) => { setNotice(message); window.setTimeout(() => setNotice(''), 3500); void fetch('http://localhost:4000/api/activity', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, message, details }) }); };
  const addLead = (lead: Omit<Lead, 'id' | 'status'>) => { const created = { ...lead, id: Date.now(), status: 'Not Dialed' }; setLeads(current => [...current, created]); setActive('Manage Leads'); act(`${lead.name} was added to your leads.`, 'lead_created', lead); void fetch('http://localhost:4000/api/leads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(created) }); };
  return <main className="app-shell"><Sidebar active={active} setActive={setActive} accountOpen={accountOpen} setAccountOpen={setAccountOpen}/><section className="workspace"><header className="page-head"><div><h1>{active}</h1><p>{descriptions[active]}</p></div>{active === 'Manage Leads' && <button className="primary mini" onClick={() => setImportOpen(true)}>＋ Import CSV</button>}</header>{notice && <div className="toast">✓ {notice}</div>}<View active={active} leads={leads} setLeads={setLeads} addLead={addLead} act={act} openImporter={() => setImportOpen(true)} /> </section>{importOpen && <ImportModal close={() => setImportOpen(false)} onRecords={records => { setLeads(current => [...current, ...records.map((r, i) => ({ id: Date.now() + i, name: r.name || 'Unnamed lead', email: r.email || '', phone: [r.country_code, r.mobile_without_country_code].filter(Boolean).join(' '), company: r.company || '—', status: r.crm_status || 'Not Dialed' }))]); act(`${records.length} parsed leads were added.`); }}/>}</main>;
}
const descriptions: Record<Section, string> = { Dashboard: 'Your team’s lead activity and performance at a glance.', 'Generate Leads': 'Create a lead manually and add it directly to your CRM.', 'Manage Leads': 'Review, import, and update every lead in your pipeline.', 'Engage Leads': 'Prioritize follow-ups and keep conversations moving.', 'Team Members': 'Invite and manage the people who work your leads.', 'Lead Sources': 'Connect and track the channels that deliver your leads.', 'Ad Accounts': 'Link ad platforms for campaign attribution.', 'WhatsApp Account': 'Connect WhatsApp to engage leads faster.', 'Tele Calling': 'Start calls and record every outcome.', 'CRM Fields': 'Customize the information captured for every lead.', 'API Center': 'Create credentials and integrate GrowEasy with your stack.', 'Business Center': 'Manage your organization, billing, and workspace-level preferences.', 'Account Settings': 'Update the Test Corp workspace and owner access settings.' };

function Sidebar({ active, setActive, accountOpen, setAccountOpen }: { active: Section; setActive: (s: Section) => void; accountOpen: boolean; setAccountOpen: (v: boolean) => void }) { return <aside><div className="brand"><i>↗</i> GrowEasy</div><button className="account" onClick={() => setAccountOpen(!accountOpen)}><b>◈</b><span>Test Corp<small>OWNER</small></span><em>⌄</em></button>{accountOpen && <div className="account-menu"><button className="workspace-button" onClick={() => { setActive('Business Center'); setAccountOpen(false); }}><b>Test Corp workspace</b><span>Owner access enabled</span></button><button onClick={() => { setActive('Account Settings'); setAccountOpen(false); }}>Account settings</button></div>}{['MAIN', 'CONTROL CENTER'].map(group => <div key={group}><p className="nav-label">{group}</p>{sections.filter(x => x.group === group).map(item => <button key={item.label} className={`nav ${active === item.label ? 'selected' : ''}`} onClick={() => setActive(item.label)}><i>{item.icon}</i>{item.label}</button>)}</div>)}<button className={`business ${active === 'Business Center' ? 'selected' : ''}`} onClick={() => setActive('Business Center')}>◉ &nbsp; Business Center</button></aside> }

function View({ active, leads, setLeads, addLead, act, openImporter }: { active: Section; leads: Lead[]; setLeads: React.Dispatch<React.SetStateAction<Lead[]>>; addLead: (lead: Omit<Lead, 'id' | 'status'>) => void; act: (m: string) => void; openImporter: () => void }) {
  if (active === 'Dashboard') return <Dashboard leads={leads} setActive={() => {}}/>;
  if (active === 'Generate Leads') return <GenerateLead addLead={addLead}/>;
  if (active === 'Manage Leads') return <ManageLeads leads={leads} setLeads={setLeads} act={act} openImporter={openImporter}/>;
  if (active === 'Engage Leads') return <Engage leads={leads} setLeads={setLeads} act={act}/>;
  if (active === 'Team Members') return <Team act={act}/>;
  if (active === 'Lead Sources') return <LeadSources act={act}/>;
  if (active === 'Ad Accounts') return <AdAccounts act={act}/>;
  if (active === 'WhatsApp Account') return <Connection title="WhatsApp Business" text="Connect a WhatsApp Business number to message leads." action="Connect WhatsApp" act={act}/>;
  if (active === 'Tele Calling') return <Calling leads={leads} setLeads={setLeads} act={act}/>;
  if (active === 'CRM Fields') return <Fields act={act}/>;
  if (active === 'Business Center') return <BusinessCenter act={act}/>;
  if (active === 'Account Settings') return <AccountSettings act={act}/>;
  return <ApiCenter act={act}/>;
}
function Dashboard({ leads }: { leads: Lead[]; setActive: () => void }) { return <><div className="stat-grid"><Stat label="Total leads" value={String(leads.length)} /><Stat label="Needs follow-up" value={String(leads.filter(x => x.status !== 'Good Lead').length)} /><Stat label="Converted" value="0" /></div><section className="panel"><h2>Recent leads</h2><LeadTable leads={leads.slice(-5)} /></section></> }
function Stat({ label, value }: { label: string; value: string }) { return <div className="stat"><span>{label}</span><b>{value}</b><small>Updated just now</small></div> }
function GenerateLead({ addLead }: { addLead: (lead: Omit<Lead, 'id' | 'status'>) => void }) { const [form, setForm] = useState({ name: '', email: '', phone: '', company: '' }); return <section className="panel form-panel"><h2>Create a lead</h2><p>Enter at least an email address or mobile number.</p><Form fields={form} setFields={setForm}/><button className="primary" disabled={!form.email && !form.phone} onClick={() => { addLead(form); setForm({ name: '', email: '', phone: '', company: '' }); }}>Create lead</button></section> }
function Form({ fields, setFields }: { fields: { name: string; email: string; phone: string; company: string }; setFields: React.Dispatch<React.SetStateAction<{ name: string; email: string; phone: string; company: string }>> }) { return <div className="form-grid">{Object.entries(fields).map(([key, value]) => <label key={key}>{key === 'phone' ? 'Mobile number' : key[0].toUpperCase() + key.slice(1)}<input value={value} placeholder={`Enter ${key}`} onChange={e => setFields(current => ({ ...current, [key]: e.target.value }))}/></label>)}</div> }
function ManageLeads({ leads, setLeads, act, openImporter }: { leads: Lead[]; setLeads: React.Dispatch<React.SetStateAction<Lead[]>>; act: (m: string) => void; openImporter: () => void }) { const [query, setQuery] = useState(''); const visible = useMemo(() => leads.filter(x => `${x.name} ${x.email} ${x.phone}`.toLowerCase().includes(query.toLowerCase())), [leads, query]); return <section className="panel"><div className="toolbar"><h2>Your Leads <small>{leads.length} total</small></h2><div><input className="search-input" placeholder="Search email or phone…" value={query} onChange={e => setQuery(e.target.value)}/><button className="secondary" onClick={openImporter}>Import CSV</button></div></div><LeadTable leads={visible} onStatus={(id, status) => { setLeads(current => current.map(x => x.id === id ? { ...x, status } : x)); act('Lead status updated.'); }}/></section> }
function LeadTable({ leads, onStatus }: { leads: Lead[]; onStatus?: (id: number, status: string) => void }) { return <div className="table-wrap"><table><thead><tr><th>Lead name</th><th>Email</th><th>Contact</th><th>Company</th><th>Status</th><th>Actions</th></tr></thead><tbody>{leads.map(lead => <tr key={lead.id}><td>{lead.name}</td><td>{lead.email || '—'}</td><td>{lead.phone || '—'}</td><td>{lead.company}</td><td><mark>{lead.status}</mark></td><td>{onStatus ? <select value={lead.status} onChange={e => onStatus(lead.id, e.target.value)}><option>Not Dialed</option><option>Good Lead</option><option>Follow up</option><option>Bad Lead</option><option>Sale Done</option></select> : '—'}</td></tr>)}</tbody></table>{!leads.length && <p className="empty">No leads match this search.</p>}</div> }
function Engage({ leads, setLeads, act }: { leads: Lead[]; setLeads: React.Dispatch<React.SetStateAction<Lead[]>>; act: (m: string) => void }) { return <section className="panel"><h2>Follow-up queue</h2><p>Choose an action for a lead. The status updates immediately.</p>{leads.map(lead => <div className="action-row" key={lead.id}><span><b>{lead.name}</b><small>{lead.email || lead.phone}</small></span><button className="secondary" onClick={() => { setLeads(x => x.map(item => item.id === lead.id ? { ...item, status: 'Follow up' } : item)); act(`Follow-up scheduled for ${lead.name}.`); }}>Schedule follow-up</button><button className="primary mini" onClick={() => act(`Message composer opened for ${lead.name}.`)}>Message</button></div>)}</section> }
function Team({ act }: { act: (m: string) => void }) { const [members, setMembers] = useState(['VK Test']); const [name, setName] = useState(''); return <section className="panel"><div className="toolbar"><h2>Team members</h2><div><input className="search-input" placeholder="Name or email" value={name} onChange={e => setName(e.target.value)}/><button className="primary mini" onClick={() => { if (name.trim()) { setMembers(x => [...x, name]); setName(''); act('Team invitation created.'); } }}>Invite</button></div></div>{members.map(member => <div className="action-row" key={member}><span><b>{member}</b><small>Lead manager · Active</small></span><button className="secondary" onClick={() => act(`${member}'s role settings opened.`)}>Manage role</button></div>)}</section> }
function LeadSources({ act }: { act: (m: string) => void }) { const [sources, setSources] = useState(['Google Ads', 'Facebook Leads']); const [source, setSource] = useState(''); return <section className="panel"><h2>Active lead sources</h2><p>Sources make reporting and lead attribution reliable.</p><div className="add-line"><input placeholder="New source name" value={source} onChange={e => setSource(e.target.value)}/><button className="primary mini" onClick={() => { if (source.trim()) { setSources(x => [...x, source]); setSource(''); act('Lead source added.'); } }}>Add source</button></div>{sources.map(x => <div className="action-row" key={x}><span><b>{x}</b><small>Connected · Active</small></span><button className="secondary" onClick={() => act(`${x} settings opened.`)}>Configure</button></div>)}</section> }
function AdAccounts({ act }: { act: (m: string) => void }) { const [connected, setConnected] = useState<string[]>([]); return <section className="panel"><h2>Advertising accounts</h2>{['Google Ads', 'Meta Ads'].map(name => <div className="action-row" key={name}><span><b>{name}</b><small>{connected.includes(name) ? 'Connected' : 'Not connected'}</small></span><button className={connected.includes(name) ? 'secondary' : 'primary mini'} onClick={() => { if (!connected.includes(name)) setConnected(x => [...x, name]); act(connected.includes(name) ? `${name} settings opened.` : `${name} connected successfully.`); }}>{connected.includes(name) ? 'Manage' : 'Connect'}</button></div>)}</section> }
function Connection({ title, text, action, act }: { title: string; text: string; action: string; act: (m: string) => void }) { const [connected, setConnected] = useState(false); return <section className="panel connection"><div className="connection-icon">▱</div><h2>{title}</h2><p>{text}</p><button className="primary" onClick={() => { setConnected(true); act(`${title} connected successfully.`); }}>{connected ? 'Connected ✓' : action}</button></section> }
function Calling({ leads, setLeads, act }: { leads: Lead[]; setLeads: React.Dispatch<React.SetStateAction<Lead[]>>; act: (m: string) => void }) { const [selected, setSelected] = useState(leads[0]?.id || 0); const lead = leads.find(x => x.id === selected); return <section className="panel connection"><div className="connection-icon">◉</div><h2>Tele Calling</h2><p>Select a lead, then log a call outcome.</p><select className="call-select" value={selected} onChange={e => setSelected(Number(e.target.value))}>{leads.map(x => <option key={x.id} value={x.id}>{x.name} · {x.phone || x.email}</option>)}</select><div className="call-actions"><button className="secondary" onClick={() => act(`Calling ${lead?.name || 'lead'}…`)}>Start call</button><button className="primary" onClick={() => { if (lead) setLeads(x => x.map(item => item.id === lead.id ? { ...item, status: 'Good Lead' } : item)); act('Call outcome saved as Good Lead.'); }}>Mark good lead</button></div></section> }
function Fields({ act }: { act: (m: string) => void }) { const [fields, setFields] = useState(['Name', 'Email', 'Mobile number', 'Company', 'Lead status']); const [field, setField] = useState(''); return <section className="panel"><h2>CRM fields</h2><div className="add-line"><input placeholder="New custom field" value={field} onChange={e => setField(e.target.value)}/><button className="primary mini" onClick={() => { if (field.trim()) { setFields(x => [...x, field]); setField(''); act('Custom CRM field created.'); } }}>Add field</button></div>{fields.map(x => <div className="action-row" key={x}><span><b>{x}</b><small>Text field · Visible on lead profiles</small></span><button className="secondary" onClick={() => act(`${x} field settings opened.`)}>Edit</button></div>)}</section> }
function ApiCenter({ act }: { act: (m: string) => void }) { const [token, setToken] = useState(''); return <section className="panel connection"><div className="connection-icon">⌁</div><h2>API Center</h2><p>Create a secure key for server-side GrowEasy integrations.</p>{token ? <code>{token}</code> : <button className="primary" onClick={() => { const value = `ge_live_${crypto.randomUUID().replaceAll('-', '').slice(0, 24)}`; setToken(value); act('A new API key was created. Copy it now.'); }}>Create API key</button>}{token && <button className="secondary" onClick={() => { navigator.clipboard?.writeText(token); act('API key copied to clipboard.'); }}>Copy API key</button>}</section> }
function BusinessCenter({ act }: { act: (m: string, type?: string, details?: Record<string, unknown>) => void }) { const [plan, setPlan] = useState('Growth'); return <><div className="stat-grid"><Stat label="Workspace" value="Test Corp"/><Stat label="Plan" value={plan}/><Stat label="Team seats" value="1 / 5"/></div><section className="panel"><h2>Business Center</h2><p>Manage the Test Corp workspace in one place.</p><div className="action-row"><span><b>Workspace plan</b><small>{plan} plan · Renews monthly</small></span><button className="secondary" onClick={() => { const next = plan === 'Growth' ? 'Scale' : 'Growth'; setPlan(next); void fetch('http://localhost:4000/api/workspace', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ plan: next }) }); act('Workspace plan updated.', 'workspace_plan', { plan: next }); }}>Change plan</button></div><div className="action-row"><span><b>Billing notifications</b><small>Sent to the workspace owner</small></span><button className="secondary" onClick={() => act('Billing notification preferences saved.', 'billing_preferences')}>Configure</button></div><div className="action-row"><span><b>Workspace data export</b><small>Download leads and settings for Test Corp</small></span><button className="primary mini" onClick={() => act('Your workspace export is being prepared.', 'workspace_export')}>Request export</button></div></section></> }
function AccountSettings({ act }: { act: (m: string, type?: string, details?: Record<string, unknown>) => void }) { const [name, setName] = useState('Test Corp'); const [email, setEmail] = useState('owner@testcorp.com'); const [access, setAccess] = useState(true); const save = () => { void fetch('http://localhost:4000/api/workspace', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, ownerEmail: email, ownerAccess: access }) }); act(`${name} account settings saved.`, 'workspace_settings', { name, ownerEmail: email, ownerAccess: access }); }; return <section className="panel form-panel"><h2>Account settings</h2><p>Test Corp workspace · Owner access enabled</p><div className="form-grid"><label>Workspace name<input value={name} onChange={e => setName(e.target.value)}/></label><label>Owner email<input value={email} onChange={e => setEmail(e.target.value)}/></label></div><div className="action-row"><span><b>Owner access</b><small>{access ? 'Full workspace permissions enabled' : 'Limited permissions'}</small></span><button className="secondary" onClick={() => setAccess(x => !x)}>{access ? 'Disable' : 'Enable'}</button></div><button className="primary" onClick={save}>Save changes</button></section> }

function ImportModal({ close, onRecords }: { close: () => void; onRecords: (records: Row[]) => void }) { const [file, setFile] = useState<File>(); const [rows, setRows] = useState<Row[]>([]); const [result, setResult] = useState<Result>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const load = (f?: File) => { if (!f) return; if (!f.name.toLowerCase().endsWith('.csv')) return setError('Please choose a CSV file.'); setFile(f); setError(''); Papa.parse<Row>(f, { header: true, skipEmptyLines: true, complete: r => setRows(r.data), error: () => setError('We could not read that CSV.') }); }; const upload = async () => { if (!file) return; setLoading(true); try { const body = new FormData(); body.append('file', file); const response = await fetch('http://localhost:4000/api/import', { method: 'POST', body }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); } catch (e) { setError(e instanceof Error ? e.message : 'Import failed.'); } finally { setLoading(false); } }; const headers = (result?.records[0] ? Object.keys(result.records[0]) : rows[0] ? Object.keys(rows[0]) : []); const tableRows = result?.records || rows; return <div className="overlay"><section className="modal"><button className="close" onClick={close}>×</button><h2>{result ? 'Import complete' : 'Import Leads via CSV'}</h2><p className="sub">{result ? `${result.totalImported} leads parsed · ${result.totalSkipped} skipped` : 'Upload a CSV file to bulk import leads into your system.'}</p>{!file && !result ? <label className="upload" onDragOver={e => e.preventDefault()} onDrop={(e: DragEvent) => { e.preventDefault(); load(e.dataTransfer.files[0]); }}><input type="file" accept=".csv,text/csv" onChange={(e: ChangeEvent<HTMLInputElement>) => load(e.target.files?.[0])}/><span className="upload-icon">↑</span><strong>Drop your CSV file here</strong><small>or click to browse files</small><em>Supported file: .csv (max 10MB)</em></label> : <>{file && !result && <div className="file"><span>▧</span><div><b>{file.name}</b><small>{rows.length} rows ready to import</small></div></div>}{tableRows.length > 0 && <CsvTable headers={headers} rows={tableRows}/>}</>}{error && <p className="error">{error}</p>}<footer>{result ? <><button className="cancel" onClick={close}>Close</button><button className="primary" onClick={() => { onRecords(result.records); close(); }}>Add to leads</button></> : <><button className="cancel" onClick={close}>Cancel</button><button className="primary" disabled={!file || loading} onClick={upload}>{loading ? 'Extracting…' : 'Upload File'}</button></>}</footer></section></div> }
function CsvTable({ headers, rows }: { headers: string[]; rows: Row[] }) { return <div className="table-wrap import-table"><table><thead><tr>{headers.map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{rows.slice(0, 100).map((row, i) => <tr key={i}>{headers.map(x => <td key={x}>{row[x] || '—'}</td>)}</tr>)}</tbody></table></div> }
